### ISSUE TITLE
CSS media query weird match behavior using min-width

### ISSUE THREAD

**Issue by amankkg** [manojVivek/responsively-app#302]
# environment
Responsively 0.6.1
Ubuntu 20.04 based Linux

# problem
In order to match a device width using `(min-width: 768px)` (iPad) media query I have to write 762 instead of 768. Same with other values for given rule.

## reproduction

Let's match 5 built-in devices: iPhone 5/SE (default, 320x568), iPhone X (375x812), iPad (768x1024), iPad Pro (1024x1366), Laptop HiDPI (1440x900)

### markup
```html
<div class="test"></div>
```

### media queries (original)

Note: I use PostCSS nested properties syntax for brevity, but it behaves the same with correct CSS3 version
```css
body {
  margin: 0;
}

.test {
  width: 100vw;
  height: 100vh;
  background: white;

  @media (min-width: 375px) {
    background: purple;
  }

  @media (min-width: 768px) {
    background: red;
  }

  @media (min-width: 1024px) {
    background: green;
  }

  @media (min-width: 1440px) {
    background: blue;
  }
}
```

#### result (colors mismatch)

![Screenshot from 2020-07-10 18-16-32](https://user-images.githubusercontent.com/3933028/87153740-c2327580-c2d9-11ea-920a-633422044486.png)

### media queries (subtracted 6px)

```css
.test {
  width: 100vw;
  height: 100vh;
  background: white;

  @media (min-width: 369px) {
    background: purple;
  }

  @media (min-width: 762px) {
    background: red;
  }

  @media (min-width: 1018px) {
    background: green;
  }

  @media (min-width: 1434px) {
    background: blue;
  }
}
```

#### result (now colors match)

![Screenshot from 2020-07-10 18-17-29](https://user-images.githubusercontent.com/3933028/87153792-d9716300-c2d9-11ea-86c7-344506b0a181.png)

PS: images are clickable

**Update**: added app version
